all:

OPENFST_CXXFLAGS = 
OPENFST_LDLIBS = 
include ../kaldi.mk

TESTFILES = 

OBJFILES = vts-first-order.o vts-accum-diag-gmm.o vts-accum-am-diag-gmm.o

LIBNAME = kaldi-vts

ADDLIBS = ../tree/kaldi-tree.a ../util/kaldi-util.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a ../gmm/kaldi-gmm.a

include ../makefiles/default_rules.mk
