all:

include ../kaldi.mk

TESTFILES = hmm-topology-test hmm-utils-test

OBJFILES = hmm-topology.o transition-model.o hmm-utils.o tree-accu.o

LIBNAME = kaldi-hmm

ADDLIBS = ../tree/kaldi-tree.a ../base/kaldi-base.a ../matrix/kaldi-matrix.a 

include ../makefiles/default_rules.mk


