

all:

include ../kaldi.mk

TESTFILES = nnet-test

OBJFILES = nnet-nnet.o nnet-component.o nnet-loss.o nnet-rnnlm.o

LIBNAME = kaldi-nnet

ADDLIBS = ../matrix/kaldi-matrix.a ../base/kaldi-base.a  ../util/kaldi-util.a 

include ../makefiles/default_rules.mk


